scalar DateTime
scalar Upload

type File {
  id: ID!
  path: String!
  filename: String!
  mimetype: String!
  encoding: String!
}

type Podcast {
  id: Int!
  author: Author
  title: String!
  description: String
  label: String
  genre: Genre
  bpm: Int
  duration: Int
  thumbnail: String
  date: DateTime
}

type Query {
  getPodcasts: [Podcast!]
}

input PodcastInput {
  author: Int!
  title: String!
  description: String
  label: Int
  genre: Int
  bpm: Int,
  duration: Int,
  thumbnail: Upload,
  date: DateTime
}

type Mutation {
  addPodcast (input: PodcastInput!): Podcast!
}
